### ISSUE TITLE
[dependency-track] add annotations support for service accounts

### ISSUE THREAD

**Issue by akath19** [evryfs/helm-charts#102]
Hi!

We need to add annotations to dependency-track service accounts to allow IAM permisions in GKE, these annotations are required to allow access to CloudSQL databases.

**Is your feature request related to a problem? Please describe.**
Not having annotations in the SAs would mean we need to add long-live, non-auditable JSON files for authentication

**Describe the solution you'd like**
Add suppport for annotations on service accounts

**Describe alternatives you've considered**
Using long-lived, non-auditable JSON files as mounts on sidecars

**Comment by davidkarlsen** [comment]
👍
Do you want to provide a PR?

**Comment by akath19** [comment]
Done!, I had to learn how to sign commits to fulfill the DCO
