### ISSUE TITLE
[dependency-track] need to be able to specify `ingress.spec.ingressClassName`

### ISSUE THREAD

**Issue by jimmythedog** [evryfs/helm-charts#128]
**Is your feature request related to a problem? Please describe.**
We are running multiple `ingressclasses`, so we need to be able to specify the [`spec.ingressClassName`](https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation) on the `ingress`

**Describe the solution you'd like**
To be able to specify `ingress.ingressClassName` in the helm `values.yaml` file - this would then generate a `spec.ingressClassName` entry in the `ingress`, with the value that was specified in the `values.yaml` file

**Describe alternatives you've considered**
None really TBH - the deprecated `kubernetes.io/ingress.class` annotation no longer works on the latest controllers

**Additional context**

**Comment by davidkarlsen** [comment]
Fixed in #129
