### ISSUE TITLE
Dependency Track - README needs updating

### ISSUE THREAD

**Issue by mtcolman** [evryfs/helm-charts#137]
Hi, I believe you need to update the dependency track [README](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/README.md) with the new `version` and `appVersion` badges/tags.

Also, would it be worth including a link to the [Dependency Track Change Log](https://docs.dependencytrack.org/changelog/) so that users of the chart are aware of breaking changes/things they need to know prior to upgrading the chart? Thanks!

**Comment by davidkarlsen** [comment]
@othar use the helm-docs pre-commit hook and this will be autogenerated.

**Comment by davidkarlsen** [comment]
Fixed in recent release
