### ISSUE TITLE
Empty home/dashboard after upgrade

### ISSUE THREAD

**Issue by wargamez** [evryfs/helm-charts#151]
After upgrading to the chart having split between api and frontend the frontend has no content on the home/dashboard, all other pages seems correct. Any idea what this could be?
![image](https://user-images.githubusercontent.com/76409/157222142-9c1e7a18-52a7-49e4-98cb-5be3c84a7d60.png)

**Comment by davidkarlsen** [comment]
@wargamez try opening a case with https://github.com/DependencyTrack/dependency-track
