### ISSUE TITLE
[evryfs-oss/ecr-proxy] Not able to use IAM role

### ISSUE THREAD

**Issue by varunpalekar** [evryfs/helm-charts#17]
**Describe the bug**
Not able to use `ecr-proxy` helm chart with IAM Role, without defining `awsAccessKeyId` and `awsSecretAccessKey`.

**Version of Helm and Kubernetes**:
Helm: `3.1.2`
Kubernetes: `1.15`

**Which chart**: `ecr-proxy:.0.2.1`

**What happened**:
Not able to use this chart by using secrets with `awsAccessKeyId` and `awsSecretAccessKey` define.

**What you expected to happen**:
Can able to deploy helm chart to use IAM role for ecr-proxy

**How to reproduce it** (as minimally and precisely as possible):
Just use AWS roles (without using access key and secret key)

**Anything else we need to know**:
This may be due usage of env variable with the name `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` in deployment. Removal of this solve the issue.
https://github.com/evryfs/helm-charts/blob/master/charts/ecr-proxy/templates/deployment.yaml#L53

I can also create an MR if needed

**Comment by davidkarlsen** [comment]
Hi, a PR would be welcomed!
The env-var section for the two vars can be conditioned like this https://github.com/evryfs/helm-charts/blob/master/charts/ecr-proxy/templates/secret.yaml#L1.

**Comment by varunpalekar** [comment]
Sure, but if we create it conditional then in README also need to update accordingly https://github.com/evryfs/helm-charts/blob/master/charts/ecr-proxy/values.yaml#L60

**Comment by davidkarlsen** [comment]
OK, published - after some CI-fighting ;-) 
https://github.com/evryfs/helm-charts/commits/master
