### ISSUE TITLE
[dependency-track] please add mirror path to ingress

### ISSUE THREAD

**Issue by panthere2k** [evryfs/helm-charts#198]
I am trying to use the nvd mirror function of dependencytrack. However, in ingress, everything except the /api path is forwarded to the front-end.
When I select the mirror path, I always get a file not found page on the front-end.

Of course I just have to change the ingress setting every time. But I want to keep the value by using the settings in helm.

Add mirror path setting to "/helm-charts/tree/master/charts/dependency-track/templates/ingress.yaml"

thanks.

**Comment by davidkarlsen** [comment]
@panthere2k good point, I was not aware of a mirroring url - do you have some docs on that feature? Maybe it has been added in a later version than the chart was designed for (or we simply did not know). I don't see a problem adding another url route for this. PRs are welcomed!
