### ISSUE TITLE
Dependency Track can`t bound volume

### ISSUE THREAD

**Issue by killerquitsche** [evryfs/helm-charts#25]
Hello everyone,
we are not able to deploy your Helm Chart for Dependency Track in our k8s cluster. The reason is that we can't connect the volume "data-dependency-track-postgresql-0" because the storageClass is not set.
Although we have set it in the values.yml.
```---
  postgresql: 
    global: 
      storageClass: "ebs"
    persistence: 
      storageClass: "ebs"
  ingress:
    enabled: true
    hosts:
      - host: xxx.yyy.com
        paths:
          - "/"
    tls: 
      - secretName: secret-tls-certificate
        hosts:
          - xxx.yyy.com
  persistentVolume:
    enabled: true
    storageClass: "ebs"
  persistence:
    enabled: true
    storageClass: "ebs"
```
Is there a value we miss here?
The volume for dependency track is bound without problems.
Many thanks in advance

**Comment by davidkarlsen** [comment]
https://github.com/bitnami/charts/blob/master/bitnami/postgresql/templates/_helpers.tpl#L356
Try:
```yaml
...
postgresql:
  persistence:
    storageClass: ebs
```

**Comment by killerquitsche** [comment]
I have tested it, but unfortunately the error remains.

**Comment by davidkarlsen** [comment]
did you uninstall and install? PVCs are immutable.

**Comment by killerquitsche** [comment]
You were right, I forgot to delete the volume which is in pending mode.
Now it works, if I use the following config:
`---
postgresql:
  persistence:
    storageClass: ebs`

Thanks a lot!
