### ISSUE TITLE
Purpose of ci directory and contents?

### ISSUE THREAD

**Issue by namloc2001** [evryfs/helm-charts#3]
Hi, just wondering if you could please share info as to the purpose of the dependency track ci directory and yamls within it, where are these used please?

Thanks,

Matt

**Comment by davidkarlsen** [comment]
Files in https://github.com/evryfs/helm-charts/tree/master/charts/dependency-track/ci are used during continuous integration testing using https://github.com/helm/chart-testing-action as seen in https://github.com/evryfs/helm-charts/actions/runs/49097240 

hope this helps!
