### ISSUE TITLE
Unable to create index directory: /data/index/vulnerability

### ISSUE THREAD

**Issue by swapnilpotnis** [evryfs/helm-charts#6]
**Describe the bug**
Installed Dependency-Track using Helm Charts. The Pod is in RUNNING state but the logs state the following error:
```
13:20:15.349 ERROR [VulnerabilityIndexer] An error occurred while adding a vulnerability to the index
java.nio.file.AccessDeniedException: /data/index
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
```

**Version of Helm and Kubernetes**:
Helm Version: 3.2.3
K8s Version: 1.18

**Which chart**:
dependency-track

**What happened**:
1. Installed Dependency-Track using Helm Charts.
2. Pod is RUNNING
3. SVC is CREATED
4. After exposing the service to an external-IP address, only the title of the website along with a Blank Web-Page is displayed.
5. Upon further debugging the issue and checking the logs of the pod, the following error is getting printed on repetative basis
`13:20:15.349 ERROR [VulnerabilityIndexer] An error occurred while adding a vulnerability to the index
java.nio.file.AccessDeniedException: /data/index
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)`

**What you expected to happen**:
Service to be UP and RUNNING and DEPENDENCY-TRACK being AVAILABLE via Exposed Service

**How to reproduce it** (as minimally and precisely as possible):
Simply install dependency-track using helm charts

**Anything else we need to know**:
Thats all about it.

**Comment by davidkarlsen** [comment]
Try giving it a persistent volume: https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/templates/pvc.yaml#L1

**Comment by swapnilpotnis** [comment]
```
 kubectl get pvc
NAME                                 STATUS   VOLUME       CAPACITY   ACCESS MODES   STORAGECLASS    AGE
chart-1591811422-dependency-track    Bound    local-pv-2   50Gi       RWO            local-storage   44h
data-chart-1591811422-postgresql-0   Bound    local-pv-1   50Gi       RWO            local-storage   44h

```

**Comment by davidkarlsen** [comment]
Which storage provider do you use? Maybe there are some snags with it?
```
k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data
drwxrwsr-x    6 root     dtrack          88 Mar 22 23:50 /data
```

**Comment by swapnilpotnis** [comment]
I have a bare-metal kind of arrangement(no cloud-provider involved) as a result of which 
`kubectl get storageclass
NAME                      PROVISIONER                    RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage (default)   kubernetes.io/no-provisioner   Delete          WaitForFirstConsumer   false                  45h`

**Comment by swapnilpotnis** [comment]
```
$ kubectl describe pvc chart-1591811422-dependency-track
Name:          chart-1591811422-dependency-track
Namespace:     default
StorageClass:  local-storage
Status:        Bound
Volume:        local-pv-2
Labels:        app.kubernetes.io/instance=chart-1591811422
               app.kubernetes.io/managed-by=Helm
               app.kubernetes.io/name=dependency-track
               app.kubernetes.io/version=3.8.0
               helm.sh/chart=dependency-track-0.2.1
Annotations:   meta.helm.sh/release-name: chart-1591811422
               meta.helm.sh/release-namespace: default
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      50Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    chart-1591811422-dependency-track-5f984c6bc5-l8pp7
Events:        <none>

```

**Comment by swapnilpotnis** [comment]
> Which storage provider do you use? Maybe there are some snags with it?
> 
> ```
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data
> drwxrwsr-x    6 root     dtrack          88 Mar 22 23:50 /data
> 
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data/index
> drwxrwsr-x    7 dtrack   dtrack          85 Mar 23 04:14 /data/index
> ```

With reference to your above observation, I stated investigating on those lines and it seems that the user as well as group owner of `/data` for me is `1001`
`$ docker exec -it c4788dcd7a3e ls -l /data
total 4
drwx------   19 1001     1001          4096 Jun 10 17:51 data
`
Trying to make sense as to who is the user:group being 1001, it turns out that postgresql also has fsgroup:1001 which sets groupID and userID to 1001
`$ grep -rnw . -e "1001"
/charts/postgresql/values.yaml:88:  fsGroup: 1001
./charts/postgresql/values.yaml:89:  runAsUser: 1001
./charts/postgresql/values.yaml:517:    runAsUser: 1001
./charts/postgresql/values-production.yaml:87:  fsGroup: 1001
./charts/postgresql/values-production.yaml:88:  runAsUser: 1001
./charts/postgresql/values-production.yaml:511:    runAsUser: 1001
./charts/postgresql/README.md:162:| `securityContext.fsGroup`                     | Group ID for the container                                                                                                                                                | `1001`                                                        |
./charts/postgresql/README.md:163:| `securityContext.runAsUser`                   | User ID for the container                                                                                                                                                 | `1001`                                                        |
./charts/postgresql/README.md:202:| `metrics.securityContext.runAsUser`           | User ID for the container for metrics                                                                                                                                     | `1001`                                                        |
`

Please do let me know if the values for me are correct or they should the same user:group as you have i.e "dtrack" but then again I couldn't anywhere in charts where the command sets the group to dtrack 
`root@abc/dependency-check-helm/dependency-track# grep -rnw . -e "dtrack"
root@abc/dependency-check-helm/dependency-track# `

**Comment by swapnilpotnis** [comment]
> Which storage provider do you use? Maybe there are some snags with it?
> 
> ```
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data
> drwxrwsr-x    6 root     dtrack          88 Mar 22 23:50 /data
> 
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data/index
> drwxrwsr-x    7 dtrack   dtrack          85 Mar 23 04:14 /data/index
> ```

Is this the output from the helm generated docker container or did you by any chance create the container from docker image of "owasp/dependency-track" ?

https://hub.docker.com/layers/owasp/dependency-track/latest/images/sha256-efc65e702ee1691bd9e04bf30a89cae0ee12ec77e9601e9e46b2bcc625e60c0a?context=explore

**Comment by davidkarlsen** [comment]
I run with the standard image as defined in the chart defaults.

**Comment by swapnilpotnis** [comment]
> Which storage provider do you use? Maybe there are some snags with it?
> 
> ```
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data
> drwxrwsr-x    6 root     dtrack          88 Mar 22 23:50 /data
> 
> k exec dependency-track-7f8cb64684-cxlnl -- ls -ld /data/index
> drwxrwsr-x    7 dtrack   dtrack          85 Mar 23 04:14 /data/index
> ```

@davidkarlsen : You were right about it. I deleted the local storage -> recreated new one's for DT and now its running Smoothly. Thank You So Much for Helm Charts :)
