### ISSUE TITLE
[dependency-track] add health probes

### ISSUE THREAD

**Issue by davidkarlsen** [evryfs/helm-charts#80]
Add liveness/readiness probes, and maybe use startupprobes:
https://blog.devgenius.io/understanding-kubernetes-probes-5daaff67599a
for the api and frontend deployments.

**Describe the solution you'd like**
Adding probes help to check that the service is in fact starting as it should and healthy.

**Describe alternatives you've considered**
N/A

**Additional context**
Related: https://github.com/evryfs/helm-charts/pull/63 but this died out.

**Comment by Otterian** [comment]
Fixed in https://github.com/evryfs/helm-charts/pull/81
